var list = [
    { hours: 5, minutes: 18, type: '11', minFromMidnight: 0 },
    { hours: 5, minutes: 33, type: '11', minFromMidnight: 0 },
    { hours: 5, minutes: 47, type: '11', minFromMidnight: 0 },
    { hours: 5, minutes: 55, type: '11', minFromMidnight: 0 },

    { hours: 6, minutes: 02, type: '11', minFromMidnight: 0 },
    { hours: 6, minutes: 10, type: '11', minFromMidnight: 0 },
    { hours: 6, minutes: 17, type: '11', minFromMidnight: 0 },
    { hours: 6, minutes: 25, type: '11', minFromMidnight: 0 },
    { hours: 6, minutes: 32, type: '11', minFromMidnight: 0 },
    { hours: 6, minutes: 40, type: '11', minFromMidnight: 0 },
    { hours: 6, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 6, minutes: 53, type: '11', minFromMidnight: 0 },

    { hours: 7, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 7, minutes: 08, type: '11', minFromMidnight: 0 },
    { hours: 7, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 7, minutes: 23, type: '11', minFromMidnight: 0 },
    { hours: 7, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 7, minutes: 38, type: '11', minFromMidnight: 0 },
    { hours: 7, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 7, minutes: 53, type: '11', minFromMidnight: 0 },

    { hours: 8, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 8, minutes: 8, type: '11', minFromMidnight: 0 },
    { hours: 8, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 8, minutes: 23, type: '11', minFromMidnight: 0 },
    { hours: 8, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 8, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 8, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 8, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 9, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 9, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 9, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 9, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 9, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 9, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 9, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 9, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 10, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 10, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 10, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 10, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 10, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 10, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 10, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 10, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 11, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 11, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 11, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 11, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 11, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 11, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 11, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 11, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 12, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 12, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 12, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 12, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 12, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 12, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 12, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 12, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 13, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 13, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 13, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 13, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 13, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 13, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 13, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 13, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 14, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 14, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 14, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 14, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 14, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 14, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 14, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 14, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 15, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 15, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 15, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 15, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 15, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 15, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 15, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 15, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 16, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 16, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 16, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 16, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 16, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 16, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 16, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 16, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 17, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 17, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 17, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 17, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 17, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 17, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 17, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 17, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 18, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 18, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 18, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 18, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 18, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 18, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 18, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 18, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 19, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 19, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 19, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 19, minutes: 22, type: '11', minFromMidnight: 0 },
    { hours: 19, minutes: 30, type: '11', minFromMidnight: 0 },
    { hours: 19, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 19, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 19, minutes: 52, type: '11', minFromMidnight: 0 },

    { hours: 20, minutes: 0, type: '11', minFromMidnight: 0 },
    { hours: 20, minutes: 7, type: '11', minFromMidnight: 0 },
    { hours: 20, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 20, minutes: 17, type: '11', minFromMidnight: 0 },
    { hours: 20, minutes: 25, type: '11', minFromMidnight: 0 },
    { hours: 20, minutes: 35, type: '11', minFromMidnight: 0 },
    { hours: 20, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 20, minutes: 47, type: '11', minFromMidnight: 0 },
    { hours: 20, minutes: 55, type: '11', minFromMidnight: 0 },

    { hours: 21, minutes: 5, type: '11', minFromMidnight: 0 },
    { hours: 21, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 21, minutes: 25, type: '11', minFromMidnight: 0 },
    { hours: 21, minutes: 35, type: '11', minFromMidnight: 0 },
    { hours: 21, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 21, minutes: 55, type: '11', minFromMidnight: 0 },

    { hours: 22, minutes: 5, type: '11', minFromMidnight: 0 },
    { hours: 22, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 22, minutes: 18, type: '11', minFromMidnight: 0 },
    { hours: 22, minutes: 25, type: '11', minFromMidnight: 0 },
    { hours: 22, minutes: 33, type: '11', minFromMidnight: 0 },
    { hours: 22, minutes: 35, type: '11', minFromMidnight: 0 },
    { hours: 22, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 22, minutes: 48, type: '11', minFromMidnight: 0 },
    { hours: 22, minutes: 55, type: '11', minFromMidnight: 0 },

    { hours: 23, minutes: 3, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 5, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 15, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 18, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 25, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 33, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 35, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 45, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 48, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 55, type: '11', minFromMidnight: 0 },
    { hours: 23, minutes: 58, type: '11', minFromMidnight: 0 },

    { hours: 0, minutes: 8, type: '11', minFromMidnight: 0 },
    { hours: 0, minutes: 14, type: '11', minFromMidnight: 0 },
    { hours: 0, minutes: 23, type: '11', minFromMidnight: 0 },
    { hours: 0, minutes: 33, type: '11', minFromMidnight: 0 },
    { hours: 0, minutes: 37, type: '11', minFromMidnight: 0 },
    { hours: 0, minutes: 42, type: '11', minFromMidnight: 0 },
    { hours: 0, minutes: 52, type: '11', minFromMidnight: 0 },

    //Forchbahn

    { hours: 5, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 5, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 6, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 6, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 6, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 6, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 7, minutes: 7, type: 'FB', minFromMidnight: 0 },
    { hours: 7, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 7, minutes: 22, type: 'FB', minFromMidnight: 0 },
    { hours: 7, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 7, minutes: 37, type: 'FB', minFromMidnight: 0 },
    { hours: 7, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 7, minutes: 52, type: 'FB', minFromMidnight: 0 },
    { hours: 7, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 8, minutes: 7, type: 'FB', minFromMidnight: 0 },
    { hours: 8, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 8, minutes: 22, type: 'FB', minFromMidnight: 0 },
    { hours: 8, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 8, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 8, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 9, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 9, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 9, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 9, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 10, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 10, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 10, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 10, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 11, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 11, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 11, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 11, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 12, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 12, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 12, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 12, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 13, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 13, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 13, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 13, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 14, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 14, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 14, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 14, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 15, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 15, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 15, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 15, minutes: 52, type: 'FB', minFromMidnight: 0 },
    { hours: 15, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 16, minutes: 7, type: 'FB', minFromMidnight: 0 },
    { hours: 16, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 16, minutes: 22, type: 'FB', minFromMidnight: 0 },
    { hours: 16, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 16, minutes: 37, type: 'FB', minFromMidnight: 0 },
    { hours: 16, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 16, minutes: 52, type: 'FB', minFromMidnight: 0 },
    { hours: 16, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 17, minutes: 7, type: 'FB', minFromMidnight: 0 },
    { hours: 17, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 17, minutes: 22, type: 'FB', minFromMidnight: 0 },
    { hours: 17, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 17, minutes: 37, type: 'FB', minFromMidnight: 0 },
    { hours: 17, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 17, minutes: 52, type: 'FB', minFromMidnight: 0 },
    { hours: 17, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 18, minutes: 7, type: 'FB', minFromMidnight: 0 },
    { hours: 18, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 18, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 18, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 18, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 19, minutes: 12, type: 'FB', minFromMidnight: 0 },
    { hours: 19, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 19, minutes: 42, type: 'FB', minFromMidnight: 0 },
    { hours: 19, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 20, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 20, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 21, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 21, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 22, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 22, minutes: 57, type: 'FB', minFromMidnight: 0 },

    { hours: 23, minutes: 27, type: 'FB', minFromMidnight: 0 },
    { hours: 23, minutes: 57, type: 'FB', minFromMidnight: 0 },

];
